SELECT 
  t1.CLIENT,
  t1."MONTH",
  AVG(t1.SUM_AMOUNT) AS AVG_AMOUNT
FROM
  (SELECT 
    SALES.CLIENT,
    TO_NUMBER(TO_CHAR(ORDER_DATE,'MM')) AS "MONTH",
    ORDER_ID,
    SUM(AMOUNT) AS SUM_AMOUNT
  FROM SALES
  GROUP BY 
    CLIENT,
    TO_NUMBER(TO_CHAR(ORDER_DATE,'MM')),
    ORDER_ID
  ) t1
GROUP BY 
  t1.CLIENT,
  t1."MONTH"
;